### ISSUE TITLE
Installation gives errors if hydra isn't installed

### ISSUE THREAD

**Issue by gvol** [justbur/emacs-vdiff#11]
I don't have hydra installed and when I installed emacs-vdiff I got lots of errors.  I think part of it has to do with the fact that defhydra is (likely) a macro.  

I thought about putting the hydra bits in another file and optionally loading that file, but I'm afraid that might not work either since package.el will try to compile them all.  I think the way many other packages do this is to have a completely separate vdiff-hydra package that depends on vdiff and hydra.

However, I wonder if it would be possible to change package.el to handle situations like this.  There was a similar thread on emacs-devel a year ago http://lists.gnu.org/archive/html/emacs-devel/2015-07/msg00175.html

**Comment by gvol** [comment]
Here is how MELPA suggests it can be done:
https://github.com/melpa/melpa#example-multiple-packages-in-one-repository

I'd be happy to make that change if you'd like.  I do think it would be cooler if package.el handled it "properly", but I'm not sure if/when I'll be able to get around to that.

**Comment by justbur** [comment]
Can you paste the errors you're seeing? Are they just compiler warnings?

**Comment by justbur** [comment]
Never mind. I decided to treat it as a real dependency. I think it's useful enough for that.
