### ISSUE TITLE
console mode show Symbol's function definition is void: define-fringe-bitmap

### ISSUE THREAD

**Issue by lecheel** [justbur/emacs-vdiff#12]
how to fixed vdiff working on emacs -nw console mode

**Comment by justbur** [comment]
Hi, I need some more info, like your version of emacs at least. Reproduction steps would be helpful too, since it doesn't seem to be an issue for me.

**Comment by lecheel** [comment]
Thanks justbur, 
   good to know ur side is working :-) 
   I'm running on ubuntu 15.10 x64
   emacs 24.5.1
   just put require(vdiff) inside init route then start "emacs -nw"

```lisp
Debugger entered--Lisp error: (void-function define-fringe-bitmap)
  define-fringe-bitmap(vdiff--vertical-bar [32] nil 8 center)
  byte-code("\300\301\302\303 \304\"\305\306\307%\210\300\310\311\312\302\303 S\304\"\"\305\306\313%\210\300\314\311\302\303 S\30$
  require(vdiff)
  eval-buffer(#<buffer  *load*-868877> nil "/home/foo/.emacs.d/le-loadpackages.el" nil t)  ; Reading at buffer position 504
  load-with-code-conversion("/home/foo/.emacs.d/le-loadpackages.el" "/home/foo/.emacs.d/le-loadpackages.el" nil nil)
  load("~/.emacs.d/le-loadpackages.el")
  eval-buffer(#<buffer  *load*> nil "/home/foo/.emacs" nil t)  ; Reading at buffer position 348
  load-with-code-conversion("/home/fo/.emacs" "/home/foo/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\30$
  command-line()
  normal-top-level()
```

**Comment by justbur** [comment]
I still can't reproduce it. I just tested on ubuntu 16.10 with emacs 24.5.1. I did exactly what you said to do.

Is this only a problem with emacs -nw? What about the gui? 

Can you find define-fringe-bitmap if you don't load vdiff and let emacs start up normally? Maybe with `C-h f define-fringe-bitmap RET`?

**Comment by lecheel** [comment]
I've only install emacs-nox package so there is no GUI available problem lack define-fringe-bitmap

**Comment by lecheel** [comment]
After build emacs 24.5 + GUI, console mode vdiff working correctly with ```emacs -nw```

**Comment by justbur** [comment]
Yes, I see that now. Thanks for reporting this. It seems to work with cfad650
