### ISSUE TITLE
Compatibility issue with emacsclient

### ISSUE THREAD

**Issue by onenightinminhangcampus** [justbur/emacs-vdiff#13]
When using vdiff alongside emacsclient, diff is not showing up until vdiff-refresh is manually called. This issue was first seen in [http://emacs.stackexchange.com/questions/30033/vdiff-refine-all-hunks-ediff-update-diffs-in-startup-eval](url).

init.el:
`(require 'package)`
`(add-to-list 'package-archives`
`             '("melpa" . "http://melpa.milkbox.net/packages/") t)`
`(package-initialize)`

`(require 'vdiff)`
`(setq vdiff-auto-refine t)`

Command line:
`emacsclient -c -e "(vdiff-files \"new1\" \"new2\")"`

1)Result in no diff showing:
![capture](https://cloud.githubusercontent.com/assets/10507180/22261903/b754546c-e2a9-11e6-9323-759393376048.JPG)

2)After manually vdiff-refresh:
![capture2](https://cloud.githubusercontent.com/assets/10507180/22261947/dd699324-e2a9-11e6-96d1-8a5fd07e1832.JPG)

Now only knowing a workaround which uses `sit-for` can partially solve it without the need of manually calling vdiff-refresh, but a drawback is that it works only starting from the second time of vdiff run:
`emacsclient -c -e "(progn (vdiff-files \"$file1\" \"$file2\") (sit-for 1))"`

**Comment by justbur** [comment]
It's unclear to me right now what exactly is happening, so I don't know the proper way to fix this. Somehow the refresh is happening too early, but using `after-make-frame-functions` is not helping. 

This workaround seems to work consistently for me. 

```
emacsclient -c -e "(vdiff-files \"FILE1\" \"FILE2\") (run-at-time 1 nil 'vdiff-refresh 'vdiff--scroll-function)"
```

I'll update if I find something better.
