### ISSUE TITLE
Vim-like keybindings - how to bind `] c` and `[ c` in evil normal state

### ISSUE THREAD

**Issue by edkolev** [justbur/emacs-vdiff#14]
Hi and thanks for this package!

I'm trying to map `] c` and `[ c` in evil normal state for next/previous hunk. This is working as expected:

```
  (define-key vdiff-mode-map (kbd "] c") 'vdiff-next-hunk)
  (define-key vdiff-mode-map (kbd "[ c") 'vdiff-previous-hunk)
```

But this isn't:
```
  (evil-define-key 'normal vdiff-mode-map (kbd "] c") 'vdiff-next-hunk)
  (evil-define-key 'normal vdiff-mode-map (kbd "[ c") 'vdiff-next-hunk)
```

Results in `] c is undefined`.

Is `evil-define-key` the proper way to bind keys for vdiff in normal evil state?

Thanks!

**Comment by justbur** [comment]
`evil-define-key` will work but it has a quirk related to minor modes (vdiff uses a minor mode). The keymaps need to be refreshed before the keys become active. This is normally not an issue, but evil doesn't "see" the minor mode get turned on and doesn't trigger the keymap refresh. They are refreshed on state changes though, so you should have your bindings active if you go in and out of insert state for example. You have two options:

  1. Force the refresh by adding `(evil-normalize-keymaps)` after you bind the keys
  2. Use `evil-define-minor-mode-key` like this
```elisp
(evil-define-minor-mode-key 'normal 'vdiff-mode (kbd "] c") 'vdiff-next-hunk)
```

**Comment by edkolev** [comment]
Thanks! I didn't know that.

I came up with these vim-like bindings (with `go`, `gp` instead of `do`, `dp` since `d` can't be bound without losing its "delete" behaviour):

```
  (evil-define-minor-mode-key 'normal 'vdiff-mode-map (kbd "] c") 'vdiff-next-hunk)
  (evil-define-minor-mode-key 'normal 'vdiff-mode-map (kbd "[ c") 'vdiff-previous-hunk)

  (evil-define-minor-mode-key 'normal 'vdiff-mode-map (kbd "z c") 'vdiff-close-fold)
  (evil-define-minor-mode-key 'normal 'vdiff-mode-map (kbd "z M") 'vdiff-close-all-folds)
  (evil-define-minor-mode-key 'normal 'vdiff-mode-map (kbd "z o") 'vdiff-open-fold)
  (evil-define-minor-mode-key 'normal 'vdiff-mode-map (kbd "z R") 'vdiff-open-all-folds)

  (evil-define-minor-mode-key 'motion 'vdiff-mode-map (kbd "g o") 'vdiff-receive-changes)
  (evil-define-minor-mode-key 'motion 'vdiff-mode-map (kbd "g p") 'vdiff-send-changes)
```

**Comment by justbur** [comment]
At some point, I am going to find a way to map `dp` and `do`, but for now I think I'll add your example to the README if you don't mind.

**Comment by edkolev** [comment]
Great, thanks!

**Comment by edkolev** [comment]
This is how I managed to map `dp` and `do`:

```
  ;; use "dp"/"do" to send/receive changes
  (define-key evil-operator-state-map "o" 'evgeni-diff-obtain)
  (define-key evil-operator-state-map "p" 'evgeni-diff-put)

  (defun evgeni-diff-obtain ()
    (interactive)
    (when (and (eq evil-this-operator 'evil-delete)
               (memq 'vdiff-mode minor-mode-list))
      (setq evil-inhibit-operator t)
      (call-interactively 'vdiff-receive-changes)))

  (defun evgeni-diff-put ()
    (interactive)
    (when (and (eq evil-this-operator 'evil-delete)
               (memq 'vdiff-mode minor-mode-list))
      (setq evil-inhibit-operator t)
      (call-interactively 'vdiff-send-changes)))
```

I used [evil-exchange](https://github.com/Dewdrops/evil-exchange) as an example.
