### ISSUE TITLE
2-way vdiff-magit-stage

### ISSUE THREAD

**Issue by noctuid** [justbur/emacs-vdiff#15]
It would be great if there was an option/way to have `vdiff-magit-stage` do a 2-way diff without the HEAD buffer (or without the buffer file; that might be useful in some cases). Most of the time I just want the diff to have the file and the index version.

**Comment by justbur** [comment]
Sure I can add that. I will probably keep the name of the existing 3-way
function for parity with magic-ediff.

**Comment by justbur** [comment]
I added this option as the variable `vdiff-magit-stage-is-2way`.

**Comment by noctuid** [comment]
Awesome, thanks. I just tried it out, and the head buffer is gone, but now there are two index buffers.

**Comment by justbur** [comment]
How are you entering the vdiff stage? I'm not seeing two index buffers if I use `vdiff-magit-dwim` on a file with unstaged changes in the magit status buffer. What I get is the index on the left and the current file on the right.

**Comment by noctuid** [comment]
The problem was caused by my values for `split-height-threshold` (nil) and `split-width-threshold` (0). If I change them to their default values, it works as expected. Specifically, setting the value of `split-width-threshold` too low causes this to happen for me.

**Comment by justbur** [comment]
Thanks. Found a bug in the layout routine. I think it should work with your settings after https://github.com/justbur/emacs-vdiff/commit/f11c7c2eeef33a0b75fe4e025818e7e672c57397

**Comment by noctuid** [comment]
Great, thanks!

**Comment by justbur** [comment]
@noctuid If you have other suggestions for vdiff-magit or vdiff in general, I'm happy to take them.

**Comment by noctuid** [comment]
I need to use it some more first, but I'll make more issues if I have any ideas for improvement. I never liked ediff; it is more limiting since you can't really work with the underlying buffers. You can always get the advantages ediff's control buffer in the vimdiff style by using something like a hydra, like this package does. My primary usage of vim for a while has been for vimdiff, so I'm really excited about vdiff, especially now that it has the same functionality as fugitive's `:Gdiff` 2-buffer staging.

**Comment by justbur** [comment]
Cool. I'm sure there are things that can improve in vdiff, too.
