### ISSUE TITLE
Not getting "addition" overlay color for added lines preceded by a line with change

### ISSUE THREAD

**Issue by jcasoliva** [justbur/emacs-vdiff#17]
Question about your screenshot:
    https://github.com/justbur/emacs-vdiff/blob/master/img/leuven.png

I noticed that if one of buffers has at least one line with a change and is missing any lines right after the line with the change, "vdiff" correctly adds the dashed lines (when vdiff-subtraction-style = full) and uses the "subtraction" face color on the buffer that is missing lines, but uses the "change" overlay color on the buffer that has extra added lines. If I use "vimdiff" instead, the line with the change is overlaid with the "change" color (same as vdiff), but the buffer with the extra lines after the changed line uses the "addition" overlay color.

Is there a way to achieve similar behavior to vimdiff for this?
Thanks so much,
Jordi

**Comment by justbur** [comment]
Try this in your init.el

```elisp
(custom-set-faces '(vdiff-subtraction-face ((t (:inherit diff-added)))))
```
