### ISSUE TITLE
alternative diff programs (e.g. patience diff)

### ISSUE THREAD

**Issue by wbolster** [justbur/emacs-vdiff#18]
hi, first of all, thanks for this nice package!

is it possible to use a diff program that could potentially produce nicer diffs, like patience diff using `git diff` in stand-alone mode (this works outside git repos)?

```
git diff --patience --no-index FILE-A FILE-B
```

i tried

```
  (setq vdiff-diff-program "git")
  (seq vdiff-diff-extra-args "diff --no-index --patience")
```

but the result is that i don't see any diffs. :(

also these extra args wouldn't make any sense for `diff3`.

**Comment by justbur** [comment]
The issue is the output format from `git diff` differs from that of the standard `diff` command. If you can find a flag to change the output to match the format from `diff`, then you should be able to use it with the existing package. Otherwise, I'll need to add a function to parse the `git diff` format (there's no reason that's not possible).

**Comment by justbur** [comment]
Actually, it looks like I should be using the unified diff output anyway (`diff -u`), so maybe I'll just switch over to supporting that format by default. That should make using other algorithms easier.

**Comment by wbolster** [comment]
ah, didn't realise that `vdiff` is not using unified diff.

fwiw, i am not even sure whether other diff algorithms will result in significantly improved real-world workflows anyway. this is what i was trying to find out actually.

also, in my very objective opinion `vdiff` is exactly 1000× nicer than `ediff`, so this ticket is not a big problem at all for me.

**Comment by justbur** [comment]
@wbolster Try the diff-u branch. By changing `vdiff-diff-program` to `git diff` and `vdiff-diff-extra-args` appropriately it *should* work now. I haven't done any real testing yet though

**Comment by justbur** [comment]
With 835485b on master, try 

```elisp
(setq vdiff-diff-algorithm 'git-diff-patience)
```

I removed the `vdiff-diff-program` variable in favor of this one. 

I'm not sure you will notice a difference, but at least the machinery is there to support other algorithms more easily.

**Comment by wbolster** [comment]
woohoo :+1:
