### ISSUE TITLE
Error after start vdiff-mode

### ISSUE THREAD

**Issue by poulpoulsen** [justbur/emacs-vdiff#19]
Hello,
after a fresh install i try to start vdiff-mode but after M-x vdiff-mode the following error occurs:

Compiling c:/Users/Held/emax/elpa/vdiff-20180627.615/vdiff.el...done
Wrote c:/Users/Held/emax/elpa/vdiff-20180627.615/vdiff.elc
Checking c:/Users/Held/emax/elpa/vdiff-20180627.615...
Done (Total of 1 file compiled, 2 skipped)
vdiff--buffer-init: Wrong type argument: vdiff-session, nil

Any clues whats going wrong?
Regards
Poul

**Comment by justbur** [comment]
Yes, `vdiff-mode` should not be used directly. It's invoked as part of the setup procedure. You start a session by using `vdiff-files` or any of the commands [listed here](https://github.com/justbur/emacs-vdiff#installation-and-usage)

**Comment by poulpoulsen** [comment]
ok, i see. Thanks.
Do i understand it correct: To access the commands via C-c i have to run a vdiff command first?
Regards
Poul

**Comment by justbur** [comment]
Yes, a typical scenario would be

 1. `M-x vdiff-files`
 2. Select first file for diff
 3. Select second file for diff

After doing that you should be presented with two buffers in `vdiff-mode`. If you use this line from the README
```elisp
(define-key vdiff-mode-map (kbd "C-c") vdiff-mode-prefix-map)
```
then the vdiff commands will be available under the `C-c` prefix.
