### ISSUE TITLE
Truncate lines

### ISSUE THREAD

**Issue by aragaer** [justbur/emacs-vdiff#21]
When comparing buffers and one of them has a very long line (and another one doesn't) whole diff becomes unaligned. This can be solved by `M-x toggle-truncate-lines` in both buffers, but I think this should be the default (it is in vim).

**Comment by justbur** [comment]
I agree. See commit 3bfb5de

**Comment by noctuid** [comment]
Shouldn't it disable truncation in the cleanup function if truncation was previously disabled?

**Comment by justbur** [comment]
@noctuid yes, see ef899b82c4df6276306f1a92d6fc5530a82690b4
