### ISSUE TITLE
Send/receive parts of changes

### ISSUE THREAD

**Issue by noctuid** [justbur/emacs-vdiff#23]
It would be nice to be able to send/receive only parts of changes (specifically, single lines like you can in vimdiff or magi)t. I thought the existing commands would do this based on the docstring, but it looks like visual selection can only be used to send/receive multiple hunks as opposed to a part of one.

**Comment by justbur** [comment]
I pushed some initial work to the selective-send branch if you want to try it. It needs some further testing.

**Comment by noctuid** [comment]
Thanks, it seems to work well from what I've tried. Will let you know if I find any issues.

**Comment by justbur** [comment]
Great, I pushed the changes required for it to work with 3way diffs just now. It's just about done, unless you find a problem
