### ISSUE TITLE
Feature request: Compare two no-file buffer

### ISSUE THREAD

**Issue by 4goodapp** [justbur/emacs-vdiff#26]
I used this service to compare two text sometimes: https://text-compare.com
Is it posible to have option to open vdiff, ready to receive two text?
The current implementation require you to create two tmp buffer for that which isn't just quick.

**Comment by justbur** [comment]
You want a function for vdiff that creates two buffers to paste text into?

**Comment by 4goodapp** [comment]
Yes, Exactly.
something like this ready to receive texts from lets say, clipboard 
<img width="1126" alt="Screen Shot 2020-01-20 at 19 19 16" src="https://user-images.githubusercontent.com/6249230/72752305-c4810600-3bb9-11ea-993d-4130af76852c.png">

**Comment by edkolev** [comment]
A wrapper like vim's linediff might make sense https://github.com/AndrewRadev/linediff.vim

Sorry for tailgating another feature request I would like to discuss - would it be simple to support diff-ing narrowed buffers? I could do a PR, as long as there isn't a conceptual issue with this approach.

**Comment by 4goodapp** [comment]
Yes, something like that exactly 😀.

> diff-ing narrowed buffers

Sorry I don't understand what you mean here.

**Comment by 4goodapp** [comment]
However, The two texts (to compare) don't necessarily need to come from Emacs or an open file  itself. It may just come from code I copied from let's Chrome web browser.

**Comment by justbur** [comment]
Would the buffers be deleted by default or kept by default? Would you want to name the buffers or give them a temporary name?

**Comment by 4goodapp** [comment]
I think a temporary name would be OK, left right, text 1 - text 2, or just whatever you may think fit better. by default of course. Maybe add options to rename them.

> Would the buffers be deleted by default or kept by default? 

Not sure what you mean here.

**Comment by justbur** [comment]
When you quit the diff, should the text be deleted or kept for future
reference?

**Comment by 4goodapp** [comment]
Yeah, why not. at least, by default yeah. Maybe not. I don't know... Chose the best, am fine with both 🙂.

**Comment by justbur** [comment]
try `vdiff-temp-files` on master

**Comment by 4goodapp** [comment]
@justbur 
Hello, Sorry for the delay, 
Thank you very much for implemting the feature 
I just test it and here is my thoughts:

When it comes to layout It works perfectly.
the auto scroll on both buffer is nice too, I didn't expect that one.

Now about the colors, Am little confused.
Like It's easy to see line that doesn't exist on the other side with the red dashes -----------
howerver on line with different text, only the color change.
An idea solution would be to use different background like in this example:

<img width="1388" alt="Screen Shot 2020-02-15 at 19 33 27" src="https://user-images.githubusercontent.com/6249230/74594492-22750200-502f-11ea-83e7-3dbcaf36823a.png">

 instead of just changing the color like in the current implementation:

<img width="1036" alt="Screen Shot 2020-02-15 at 20 01 06" src="https://user-images.githubusercontent.com/6249230/74594500-4f291980-502f-11ea-9156-28d46018cd3f.png">

**Comment by justbur** [comment]
The colors used are not set by this package. Their set by the theme you are using.

**Comment by 4goodapp** [comment]
Hello, 
`vdiff-temp-files` isn't available on Melpa yet.

**Comment by justbur** [comment]
It's been there since February. I just downloaded it again. Maybe you pinned it?

**Comment by 4goodapp** [comment]
That's weird, I just try again but `M-x vdiff-temp-files` doesn't show nothing... 
I remember it was working back in february.
