### ISSUE TITLE
Release new version on GNU ELPA

### ISSUE THREAD

**Issue by skangas** [justbur/emacs-vdiff#27]
Please consider making a new release of this package on GNU ELPA.

The version in GNU ELPA seems to be version 0.2.3 from 2017:
https://elpa.gnu.org/packages/vdiff.html

Thanks in advance.

**Comment by justbur** [comment]
I just did. Not sure how long it will take to show up

**Comment by skangas** [comment]
Thanks! It seems to have now been updated.
