### ISSUE TITLE
Toggling case / whitespace doesn't work?

### ISSUE THREAD

**Issue by billsacks** [justbur/emacs-vdiff#36]
I'm not sure if this is a user error or a true issue with the package, but I can't get toggling of case and whitespace to work.

I use If I try either `vdiff-toggle-whitespace` or `vdiff-toggle-case` with the Ivy completion framework, when I select an option, I get this error:

```
make-process--with-editor-process-filter: Wrong type argument: stringp, 45
```

Then I tried without Ivy, instead manually entering `-i` (or ` -i`) to the `vdiff-toggle-case` prompt. This avoids the error, but doesn't seem to have any effect on the diff. I am attaching the two test files I used for this, which are identical except for uppercase/lowercase. Every line shows up as a difference even after running `vdiff-toggle-case` and entering `-i`.

[file1.txt](https://github.com/justbur/emacs-vdiff/files/8335337/file1.txt)
[file2.txt](https://github.com/justbur/emacs-vdiff/files/8335338/file2.txt)

Am I doing something wrong here, or are there problems with these toggling commands? These toggling commands seem like a really great feature of vdiff!

**Comment by wwade** [comment]
I have a fix for this, I'll post a PR shortly.

```diff
diff --git a/vdiff.el b/vdiff.el
index ac07e9c..092731d 100644
--- a/vdiff.el
+++ b/vdiff.el
@@ -506,6 +506,11 @@ non-nil. Ignore folds if NO-FOLD is non-nil."
   (when vdiff-mode
     (vdiff-refresh)))

+(defun vdiff--nonempty-str-to-list (str)
+  "Return a list for a non-empty `STR' or else nil."
+  (unless (string-empty-p str)
+    (ensure-list str)))
+
 ;; * Main overlay refresh routine

 (defun vdiff-refresh (&optional post-refresh-function)
@@ -524,9 +529,9 @@ POST-REFRESH-FUNCTION is called when the process finishes."
            (ses vdiff--session)
            (cmd (append
                  base-cmd
-                 (vdiff-session-whitespace-args ses)
+                 (vdiff--nonempty-str-to-list (vdiff-session-whitespace-args ses))
                  (unless (string= (car base-cmd) "git")
-                   (vdiff-session-case-args ses))
+                   (vdiff--nonempty-str-to-list (vdiff-session-case-args ses)))
                  (list "--" tmp-a tmp-b)
                  (when tmp-c
                    (list tmp-c))))
```

**Comment by billsacks** [comment]
Thank you, @wwade !
