### ISSUE TITLE
How to start folding?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [justbur/emacs-vdiff#37]
I want to use folding for python buffers. Only folding not diff.

I'm aware of [Installation & Usage](https://github.com/justbur/emacs-vdiff/blob/master/README.org#installation-and-usage) but all "entry points" there are commands that I don't need. They all related to diff not to folding.

I am using evil-mode. When I do "z m" in a python buffer I get that message

`Enable one of the following modes for folding to work: vdiff-mode, vdiff-3way-mode, hs-minor-mode, hide-ifdef-mode, outline-mode, origami-mode `

Doing `M:` there is no `vdiff-mode`.

Installed is `20210426.155`. I also verified that `0.2.4` from elpa is not installed and interfere.

**Comment by justbur** [comment]
This package is not intended to provide folding outside of diff buffers. There are several options for folding, including built-in packages and extensions. You could try starting [here](https://melpa.org/#/?q=fold&sort=downloads&asc=false) for some ideas.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Then why does Emacs tell me about the option to use `vidff-mode` here?

**Comment by justbur** [comment]
I don't know. What do you mean emacs tells you to use `vdiff-mode` and where is it telling you that?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
As I tried to explain in the initial post. When i try to fold (because of evil-mode via `z m` (fold all)) and no folding mode is active I get the message I posted in the beginning (Enable one of the following...).

**Comment by justbur** [comment]
Oh I see. That message from evil essentially means that evil knows how to fold in `vdiff-mode`, but it doesn't mean that `vdiff-mode` is necessarily the right choice (and it's not outside of a diff). Perhaps the message could be worded in a better way, but that's a question for the evil package.
